apiVersion: v1
kind: Service

metadata:
  name: weather-forecast-service
  namespace: development
  labels:
    app: weather-forecast

spec:
  selector:
      app: weather-forecast
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
